# Service definitions

parameters:
  allegro.console_logger.force_stderr: false

services:

  Symfony\Component\Serializer\SerializerInterface:
    class: Symfony\Component\Serializer\Serializer
    factory: GoFinTech\Serializer\SerializerFactory::create

  Symfony\Component\Validator\Validator\ValidatorInterface:
    class: Symfony\Component\Validator\Validator\ValidatorInterface
    factory: GoFinTech\Serializer\ValidatorFactory::create

  Psr\Log\LoggerInterface:
    class: GoFinTech\Allegro\Implementation\ConsoleLogger
    calls:
      - method: setForceOutputToStdErr
        arguments: ['%allegro.console_logger.force_stderr%']

  GoFinTech\Allegro\AllegroApp:
    class: GoFinTech\Allegro\AllegroApp
    public: true
    synthetic: true

  serializer:
    alias: Symfony\Component\Serializer\SerializerInterface
    public: true

  validator:
    alias: Symfony\Component\Validator\Validator\ValidatorInterface
    public: true

  logger:
    alias: Psr\Log\LoggerInterface
    public: true

  app:
    alias: GoFinTech\Allegro\AllegroApp
    public: true
